ALTER TABLE user_profiles
ADD COLUMN IF NOT EXISTS education_level VARCHAR(100),
ADD COLUMN IF NOT EXISTS hometown VARCHAR(100),
ADD COLUMN IF NOT EXISTS have_kids VARCHAR(50),
ADD COLUMN IF NOT EXISTS star_sign VARCHAR(50),
ADD COLUMN IF NOT EXISTS politics VARCHAR(50),
ADD COLUMN IF NOT EXISTS religion VARCHAR(100);
