CREATE TABLE IF NOT EXISTS user_notification_preferences (
  user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  likes BOOLEAN DEFAULT TRUE,
  matches BOOLEAN DEFAULT TRUE,
  messages BOOLEAN DEFAULT TRUE,
  daily_picks BOOLEAN DEFAULT TRUE,
  product_updates BOOLEAN DEFAULT TRUE,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
